#!/usr/bin/env bash
# Bash script that configures a new Ubuntu machine to
# Install nginx on web server
# Nginx should listen on port 80

sudo apt-get -y update
sudo apt-get -y install nginx
sudo chown -R $USER:$USER /var/www/
echo "Hello World" | sudo tee /var/www/html/index.html
sudo service nginx start
