#!/usr/bin/env bash
# Bash script accepts 2 arguments [domain] & [subdomain]
# Output: The subdomain [SUB_DOMAIN] is a [RECORD_TYPE] record and points to [DESTINATION]

argc=$#
www_parser() {
	if (( $argc < 2 ))
	then
		domains=("www" "lb-01" "web-01" "web-02")
		for str in "${domains[@]}"
		do
			domain=$str.$1
			cmd=$(dig $domain)
			rec=$(echo "$cmd" | grep -A1 'ANSWER SECTION' | tail -1 | awk '{print $4}')
			dest=$(echo "$cmd" | grep -A1 'ANSWER SECTION' | tail -1 | awk '{print $5}')
			echo "The subdomain $str is a $rec record and points to $dest"
		done
	else
		domain=$2.$1
		cmd=$(dig $domain)
		rec=$(echo "$cmd" | grep -A1 'ANSWER SECTION' | tail -1 | awk '{print $4}')
                dest=$(echo "$cmd" | grep -A1 'ANSWER SECTION' | tail -1 | awk '{print $5}')
                echo "The subdomain $2 is a $rec record and points to $dest"
	fi
}

www_parser "$1" "$2"
