#!/usr/bin/env bash
# Bash script generates a MySQL dump and creates a compressed archive out of it
mysqldump -u holberton_user --password="$1" --all-databases --master-data > backup.sql
tar cfz tar.gz backup.sql
mv tar.gz `date +%d-%m-%Y.tar.gz`
