#!/usr/bin/env bash
# script to make sure that nginx runs on port 80

cd /etc/nginx/sites-available/default default;
rm default;
ln -sf /etc/nginx/sites-enabled/default default;
sudo service nginx restart
