#!/usr/bin/env bash
# This scripts print Best school 10 times but differently the 9th time

count=0

while [ $count -lt 10 ];
do
	echo "Best School";
	if [ $count -eq 8 ]
	then
		echo "Hi";
	fi
	((count++))
done
