#!/usr/bin/env bash
# This scripts print Best school 10 times but differently the 9th time

count=1

while [ $count -le 10 ];
do
	if [ $count -eq 4 ]
	then
		echo "bad luck";
	elif [ $count -eq 8 ]
	then
		echo "good luck";
	else
		echo "Best School";
	fi
	((count++))
done
