#!/usr/bin/env bash
# nginx must be running as nginx user
# nginx must be listening on all active IPs on port 8080
# You cannot use apt-get remove

sudo service nginx stop
sudo sed -i 's/80/8080' /etic/nginx/sites-enabled/default
sudo sed -i 's/#user.+\;/user nginx;/' /etc/nginx/nginx.conf
sudo chmod nginx:nginx /etc/nginx/ -R
sudo service nginx restart
