#!/usr/bin/env bash
# nginx must be running as nginx user
sudo sed -i 's/80/8080/g' /etic/nginx/sites-enabled/default
sudo sed -i 's/#user www-data/user nginx/' /etc/nginx/nginx.conf
sudo chmod 644 /etc/nginx/nginx.conf
sudo pkill apache2
sudo -u nginx service nginx restart
